task_type: CPU
params:
  learning_rate: 0.02
  l2_leaf_reg: 0.3
  bagging_temperature: 1
  min_data_in_leaf: 57
  max_bin: 494
  eval_metric: F1
  loss_function: Logloss
  od_type: Iter
  od_wait: 500
  iterations: 10000
  allow_writing_files: False
path: res/models/
name: catboost
results: 5fold-catboost-results-log-features.pkl
n_splits: 5
early_stopping_rounds: 100
search: False
seed: 42
verbose: 100
output: 5fold-catboost-ensemble-log-features.csv