defaults:
  - _self_
  - data: dataset
  - hydra: default
  - models: lightgbm
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
output:
  path: output
  predict_proba: True
  target: prediction